# Generated by Django 4.2.6 on 2025-05-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_studentprofile_emrolled_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='emrolled_teachers',
            new_name='enrolled_teachers',
        ),
    ]
