# Generated by Django 4.2.6 on 2025-05-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='seats',
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='slot',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=10),
        ),
    ]
