# Generated by Django 4.2.6 on 2025-05-05 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_question_task_studentanswer_question_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='selected_answer',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='task',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='lms.task'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'task', 'question')},
        ),
    ]
