# Generated by Django 4.2.6 on 2025-05-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_studentanswer_selected_answer_studentanswer_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
